### ISSUE TITLE
ToS linked to implicit graph prevents computation of several attributes 

### ISSUE THREAD

**Issue by lnajman** [higra/Higra#113]
That prevents computation of attributes such as perimeter.

Adding
  hg.CptHierarchy.link(ToS,  hg.get_4_adjacency_graph(size))
corrects the issue

**Comment by PerretB** [comment]
TOS is currently linked to an implicit graph which is not well handled by several tree attributes. A simple workaround is to link it to an implicit graph instead. Graph size must alos account for the ``original_size`` parameter.

Affected line is:
https://github.com/PerretB/Higra/blob/26d6cc37812ff3cd689316fe0e23d67e1516c2a9/higra/image/tree_of_shapes.py#L65
