### ISSUE TITLE
data_provider meta arguments are not propagated to  inner data_provider calls

### ISSUE THREAD

**Issue by lnajman** [higra/Higra#115]
The call to
hg.attribute_perimeter_length(t1, vertex_perimeter=vertex_contour_weight,  frontier_length=frontier_sum, no_cache=True)
should be the same as the call to 
hg.attribute_perimeter_length_partition_tree(t1, vertex_perimeter=vertex_contour_weight,  frontier_length=frontier_sum, no_cache=True)

It is not. Parameter "no_cache" is not passed to the next function.

**Comment by PerretB** [comment]
This one is a bit tricky in the general case as the data_provider does not have any simple way to know if another data_provider decorated function will be called inside the function. I think that chaining of ``data_provider`` decorated  functions should be discouraged ATM.

For the specific case of the attribute perimeter length #116 will fix it.

**Comment by PerretB** [comment]
This is mitigated by #122
