### ISSUE TITLE
Installation in windows 7  

### ISSUE THREAD

**Issue by Mirmahboub** [higra/Higra#186]
I successfully installed higra in windows 7 but when I import it I receive an error that says "ImportError: DLL load failed: The specified module could not be found." Complete process is as bellow:

C:\Users\Behzad>pip3 install higra
Collecting higra
  Using cached https://files.pythonhosted.org/packages/fb/65/ca2288db7b3050e88dd
29a476da9b53e5838921737c804b3a64dce215074/higra-0.5.1-cp36-cp36m-win_amd64.whl
Requirement already satisfied: numpy>=1.17.3 in c:\users\behzad\appdata\local\pr
ograms\python\python36\lib\site-packages (from higra)
Installing collected packages: higra
Successfully installed higra-0.5.1
You are using pip version 9.0.3, however version 20.0.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' comm
and.

C:\Users\Behzad>python3
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD6
4)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import higra
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Behzad\AppData\Local\Programs\Python\Python36\lib\site-packages
\higra\__init__.py", line 16, in <module>
    from .higram import *
ImportError: DLL load failed: The specified module could not be found.
>>>

**Comment by PerretB** [comment]
Hi Mirmahboub. I'm not sure of what's happening there. Can you check that the directory ``C:\Users\Behzad\AppData\Local\Programs\Python\Python36\lib\site-packages
\higra``
contains the files ``higram.cp36-win_amd64.pyd`` and ``tbb_higra.dll``. Can you also verify that [Visual C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48145) is installed on your system ?

**Comment by Mirmahboub** [comment]
Thanks PerretB for the answer. Solved.
Actually I had "Visual C++ Redistributable for Visual Studio 2015" installed in my machine. I reinstall it with the link that you sent. But it did not work. I found another version [here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) and installed it. Now higra is working. Thanks again.

**Comment by PerretB** [comment]
Good news and thank you for the link! I will document this for future users who might have the same issue.
