### ISSUE TITLE
Add wheels and support for python 3.12

### ISSUE THREAD

**Issue by arturo-florez** [higra/Higra#271]
Please add wheels and support for Python 3.12 that was first released 2023-10-02 according to PEP 693 – Release Schedule: https://peps.python.org/pep-0693/

Python 3.7 is now End of Life

**Comment by PerretB** [comment]
👍planned for next week

**Comment by arturo-florez** [comment]
Thanks!!!, looking forward to it!

**Comment by PerretB** [comment]
version 0.6.8 with wheels for Python 3.12 is now available on Pypi (dropped support for Python 3.7)
